### ISSUE TITLE
Can you provide "db*.splite3" files for "analysis/plots-models.ipynb"?

### ISSUE THREAD

**Issue by bynIU** [ssloxford/SatIQ#1]
Thanks for your impressive paper and well-organized code. 
I want to draw a plot for Replay Attack and I find that some database files are missing. Could you please provide "db*.splite3" files for "analysis/plots-models.ipynb"? Thanks you very much. I will be looking forward to your reply.

**Comment by jsmailes** [comment]
Hi there, glad you enjoyed the paper!

The dataset can be found at the following URL: https://zenodo.org/records/8220494. Instructions are given in `README.md` for downloading and preprocessing this dataset into `.tfrecord` files, which should work with the script.

I can see that there are a few functions in the notebook which still work with the old `db*.sqlite3` files, but these should produce the same results with the new dataset format, with a small amount of modification to load the new files instead of the old database files.

Let me know if I can help with anything else!

Best,
Joshua
